WIP support slack-desktop 3.0.2

diff --git a/slack-black-theme-patch b/slack-black-theme-patch
--- a/slack-black-theme-patch
+++ b/slack-black-theme-patch
@@ -1,69 +1,43 @@
 #!/usr/bin/env bash
 
-file="/usr/lib/slack/resources/app.asar.unpacked/src/static/index.js"
+file1="/usr/lib/slack/resources/app.asar.unpacked/src/static/index.js"
+file2="/usr/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js"
 
-if [[ ! -w "$file" ]]; then
-  echo "Cannot write to $file"
-  exit 1
-fi
+test_file() {
+	if [[ ! -w "${1}" ]]; then
+	  echo "Cannot write to ${1}"
+	  exit 1
+	fi
+}
 
-if grep -q "slack-black-theme" "$file"; then
-  echo "Already patched"
-  exit 0
-fi
+patch_file() {
+	if grep -q "slack-black-theme" "${1}"; then
+	  echo "Already patched"
+	  return
+	fi
 
-cp $file ${file}.orig
+	cp ${1} ${1}.orig
 
-cat >> $file << '_EOF'
+	cat >> ${1} << '_EOF'
 
-// First make sure the wrapper app is loaded
-document.addEventListener("DOMContentLoaded", function() {
-
-   // Then get its webviews
-   let webviews = document.querySelectorAll(".TeamView webview");
-
-   // Fetch our CSS in parallel ahead of time
-   const cssPath = 'https://cdn.rawgit.com/widget-/slack-black-theme/master/custom.css';
-   let cssPromise = fetch(cssPath).then(response => response.text());
-
-   let customCustomCSS = `
-   :root {
-      /* Modify these to change your theme colors: */
-      --primary: #09F;
-      --text: #CCC;
-      --background: #080808;
-      --background-elevated: #222;
+document.addEventListener('DOMContentLoaded', function() {
+ $.ajax({
+   url: 'https://cdn.rawgit.com/widget-/slack-black-theme/master/custom.css',
+   success: function(css) {
+     \$("<style></style>").appendTo('head').html(css);
    }
-   `
-
-   // Insert a style tag into the wrapper view
-   cssPromise.then(css => {
-      let s = document.createElement('style');
-      s.type = 'text/css';
-      s.innerHTML = css + customCustomCSS;
-      document.head.appendChild(s);
-   });
-
-   // Wait for each webview to load
-   webviews.forEach(webview => {
-      webview.addEventListener('ipc-message', message => {
-         if (message.channel == 'didFinishLoading')
-            // Finally add the CSS into the webview
-            cssPromise.then(css => {
-               let script = `
-                     let s = document.createElement('style');
-                     s.type = 'text/css';
-                     s.id = 'slack-custom-css';
-                     s.innerHTML = \`${css + customCustomCSS}\`;
-                     document.head.appendChild(s);
-                     `
-               webview.executeJavaScript(script);
-            })
-      });
-   });
+ });
 });
 
 _EOF
+}
+
+test_file "${file1}"
+test_file "${file2}"
+
+
+patch_file "${file1}"
+patch_file "${file2}"
 
 exit 0
 
